application:
  name: lanblaster-sacha-house
  port: 8000
  healthPath: /health

environments:
  staging:
    domain: staging.lanblaster.sacha.house
    noIndex: true
  production:
    domain: lanblaster.sacha.house

resources:
  cpu: 200
  memory: 128
